### ISSUE TITLE
rcute-ai error "missing requirements.txt

### ISSUE THREAD

**Issue by Bazmundi** [r-cute/rcute-ai#8]
Running python 3.8 under miniconda
following destructions on installing rcute-ai, installed dlib for 3.8 then:

```
(base) C:\Users\pierc\dev>python -m pip install rcute-ai
Collecting rcute-ai
  Using cached rcute-ai-0.1.1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\pierc\miniconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pierc\\AppData\\Local\\Temp\\pip-install-xpxjhb1p\\rcute-ai\\setup.py'"'"'; __file__='"'"'C:\\Users\\pierc\\AppData\\Local\\Temp\\pip-install-xpxjhb1p\\rcute-ai\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\pierc\AppData\Local\Temp\pip-pip-egg-info-ole8t0q0'
         cwd: C:\Users\pierc\AppData\Local\Temp\pip-install-xpxjhb1p\rcute-ai\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pierc\AppData\Local\Temp\pip-install-xpxjhb1p\rcute-ai\setup.py", line 19, in <module>
        with open(requirements_path, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hyansuper** [comment]
It can be installed with .whl file via pip
But I think something is wrong with the setup.py file and that causes requirements.txt not included in the .tar.gz install
For ffmpeg on windows: see https://github.com/r-cute/rcute-cozmars
